name: aws-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda:
    name: Build and Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build your application (if needed)
        run: npm run build

      - name: Zip Functions
        run: zip -r function.zip handleCreate handleUpdate handleRead handleDelete model.js node_modules

      - name: Deploy content to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: createOnePieceCharacter
          zip_file: ./function.zip
